### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by riggy** [tymm/command-execute#6]
Hi,

I was looking for something like this, as I want to externally call notify-send, to customize my pidgin notifications. However, the binary doesn't work for me (I have 64bit OS, Linux Mint 16). I tried to compile it myself, however it throws out a lot of html tagged garbage on the screen. I don't think it's the issue with my compiler, as I can easily compile simple 'hello world' ;)

Are you familiar with this compile issue?

**Comment by tymm** [comment]
Hey,

this is strange. The command-execute64.so file works for me on a 64bit Linux system.
What kind of processor architecture are you using?
What does pidgin/finch tell you when it wants to load the plugin?

Also the compiler shouldn't throw out html tagged garbage :)
If you send a link to your compiler output, I maybe can help you.

**Comment by riggy** [comment]
Argh... sorry, it works well. Dunno what happened, but I gave it another shot just a minute ago and it works perfectly :)

One other thing, is it possible that you could add support for some kind of interpolated tags? For example %name% for inserting contact name, etc. Similar to what skype is doing? Also, it would be great to configure it for different type of events (user logged in/out, message comming in, conference message, etc.). Just giving an idea ;)

**Comment by tymm** [comment]
If there is a need for other events like »user logged in/out« I would think about it.
IM messages and conference messages are already implemented ;)

The problem with such tags is that they would be quite a security problem since those tags are under the control of others. I will think about it though.

Since I am super busy right now with other stuff pull requests are highly appreciated ;)
